name: webdav
services:
  docker-nginx-webdav:
    #image: 0fl01/docker-nginx-webdav
    build: .
    container_name: webdav
    restart: unless-stopped
    # security_opt:
    #   - no-new-privileges:true  # Отключено - мешает доступу к файлам
    ports:
      - "192.168.1.124:8088:80"
      - "192.168.1.43:8088:80"
    volumes:
      - "/home/stfu/Torrents:/media/data:Z"
      #- "/home/stfu/Torrents:/media/data"
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

